### PR TITLE
Adds support for `v5` of the `golang-jwt` library

### LINKED ISSUE #13: go-jwt V5 Support
Hi, 

Is there any plan to do support for V5 of the go-jwt lib? I know it's only in beta at the moment. 

Thanks

### PR DESCRIPTION
**Pull request by oxisto**
Hi, 

I am one of the maintainers of http://github.com/golang-jwt/jwt. For better future maintainability, we had to change the way signing methods work slightly (see https://github.com/golang-jwt/jwt/pull/278). Instead of decoding/encoding the token in the signing method, this is now done in the library itself. This should also make code in projects like this a little bit easier and cleaner.

Fixes #13

### CODE REVIEW

**Comment by matelang** [comment]
Hi @oxisto ,

Thanks for opening this PR and for making those improvements on the golang-jwt library.
I was following also the v5 progress.

Currently I am travelling and having limited access, but I'll check this PR early next week.

Cheers!

**Comment by oxisto** [comment]
> Looking good!
> When do you think it's best to merge it in? I can see the parent lib is at 5.0.0-rc2.

Without any promises, we aim to release v5 around Easter, so hopefully very soon. I will update this to the latest v5 release version then

**Comment by matelang** [comment]
Hi @oxisto ,

There was another PR (adding support for PSS) which required a bit of a refactor, and I've managed to simplify the code.
If you have time could you please resolve the conflicts?

Now there is just one KMS SigningMethod since I've managed to remove code duplication.

If you want I am happy to do the changes, but I did not want to take this contrib from you.

Cheers!

**Comment by oxisto** [comment]
> Hi @oxisto ,
> 
> There was another PR (adding support for PSS) which required a bit of a refactor, and I've managed to simplify the code. If you have time could you please resolve the conflicts?
> 
> Now there is just one KMS SigningMethod since I've managed to remove code duplication.
> 
> If you want I am happy to do the changes, but I did not want to take this contrib from you.
> 
> Cheers!

Merging done.

**Review by matelang — APPROVED** [review]

**Pull request merged**
