### PR TITLE
Added support for PSS algorithm

### PR DESCRIPTION
**Pull request by emilpriver**
Hey, 
Did see that PSS support was missing and I am in need of it. This PR aim to add support for PSS with AWS KMS.

### CODE REVIEW

**Comment by emilpriver** [comment]
I only opened the PR for early comments, I am working on makeing all the tests work and then testing it in my own project for verification. Would love some early comment if you have any :D

**Comment by emilpriver** [comment]
I was not able to add you as a assigne @matelang so I am pinging you instead.

**Comment by matelang** [comment]
Hi @emilpriver ,

Thanks for opening this PR. I am going to take a look these days (I was on holiday last week).

Thanks,
Mate

**Comment by matelang** [comment]
Hi @emilpriver ,

I've taken a look at the RSA PSS support on AWS KMS and also the draft implementation.

I am wondering whether we need to actually expose the PSS as a new signing method?

I personally would prefer if we'd register those algos in the already existing RSA KMS signing method. For clarity I'd rename the PKCS instances as well as follows (final variant in `init.go`):
```golang
	SigningMethodRSPKCS1256 *RSASigningMethod
	SigningMethodRSPKCS1384 *RSASigningMethod
	SigningMethodRSPKCS1512 *RSASigningMethod

	SigningMethodRSPSS256 *RSASigningMethod
	SigningMethodRSPSS384 *RSASigningMethod
	SigningMethodRSPSS512 *RSASigningMethod
```

At that point signing and verifying via KMS would work as expected, also falling back to the official non-KMS JWT path would work (since the fallback methods are well set up), but we'd need to cater for the local verification method with the cached KMS pubkey.

So I think it's enough to just add branching on that in the localVerify part, like:
```
if (algo is RSA PKCS){
  localVerifyRSAPKCS(...)
}
else if (algo is RSA PSS){
  localVerifyRSAPSS(...)
}
else {
  return err //just for safety
}
```

WDYT?

**Comment by emilpriver** [comment]
> Hi @emilpriver ,
> 
> I've taken a look at the RSA PSS support on AWS KMS and also the draft implementation.
> 
> I am wondering whether we need to actually expose the PSS as a new signing method?
> 
> I personally would prefer if we'd register those algos in the already existing RSA KMS signing method. For clarity I'd rename the PKCS instances as well as follows (final variant in `init.go`):
> 
> ```go
> 	SigningMethodRSPKCS1256 *RSASigningMethod
> 	SigningMethodRSPKCS1384 *RSASigningMethod
> 	SigningMethodRSPKCS1512 *RSASigningMethod
> 
> 	SigningMethodRSPSS256 *RSASigningMethod
> 	SigningMethodRSPSS384 *RSASigningMethod
> 	SigningMethodRSPSS512 *RSASigningMethod
> ```
> 
> At that point signing and verifying via KMS would work as expected, also falling back to the official non-KMS JWT path would work (since the fallback methods are well set up), but we'd need to cater for the local verification method with the cached KMS pubkey.
> 
> So I think it's enough to just add branching on that in the localVerify part, like:
> 
> ```
> if (algo is RSA PKCS){
>   localVerifyRSAPKCS(...)
> }
> else if (algo is RSA PSS){
>   localVerifyRSAPSS(...)
> }
> else {
>   return err //just for safety
> }
> ```
> 
> WDYT?

You mean that we read the "alg" header and use pss if alg is pss?

**Comment by matelang** [comment]
> > WDYT?
> 
> You mean that we read the "alg" header and use pss if alg is pss?

Yes, exactly. On local verification just check alg and use PSS.

**Comment by emilpriver** [comment]
> > > WDYT?
> > 
> > 
> > You mean that we read the "alg" header and use pss if alg is pss?
> 
> Yes, exactly. On local verification just check alg and use PSS.

Sure thing! Adding it :D

**Comment by emilpriver** [comment]
there is some problems with this when I did look into it, we know what algo the payload is AFTER we have verified it which means that all PSS types will fail haha. The algo we would be able to read is always "RSASSA_PKCS1_V1_5_SHA_XXX". So it looks like we need to expose PSS still so that we are able to verify the payload.

**Comment by emilpriver** [comment]
Or do you have a good solution that might make it possible to verify reading the "alg" header?

**Comment by matelang** [comment]
It is a bit more complicated than expected, but I tried to do many improvements since the code duplication started to get out of hand.

WDYT about this branch? It's quite in a messy state yet:
https://github.com/matelang/jwt-go-aws-kms/tree/chore/refactor

**Comment by emilpriver** [comment]
> It is a bit more complicated than expected, but I tried to do many improvements since the code duplication started to get out of hand.
> 
> WDYT about this branch? It's quite in a messy state yet: https://github.com/matelang/jwt-go-aws-kms/tree/chore/refactor

I like it! Sounds as a good solution. Then we are able to remove a bunch of code for EDSA and RSA as well. Nice work! :D

**Comment by matelang** [comment]
Hi @emilpriver ,

I've cleaned up that branch and opened a PR, also added unit tests for PS SigningMethods.
If you have any additional feedback, it's welcome.

I am going to close this PR, since https://github.com/matelang/jwt-go-aws-kms/pull/16 is going to resolve the issue as well. But thanks for opening it, it gave me the inspo to improve on the libs structure.

Cheers!

**Pull request closed without merging**
